### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by zhangfq-chemistry** [HarrievG/BGFXTest#2]
I git && cd  BGFXText &&mkdir build && cd build && cmake ../
I have installed bgfx.cmake successfully on my ubuntu.
the error:
 By not providing "FindBX.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "BX", but CMake did
  not find one.

  Could not find a package configuration file provided by "BX" with any of
  the following names:

    BXConfig.cmake
    bx-config.cmake

  Add the installation prefix of "BX" to CMAKE_PREFIX_PATH or set "BX_DIR" to
  a directory containing one of the above files.  If "BX" provides a separate
  development package or SDK, be sure it has been installed.

**Comment by HarrievG** [comment]
Please don't open any new issues , I have explained what you need to do in the "help" issue you created last week.
